[tool.towncrier]
name = "depcheck"
directory = "./docs/newsfragments"
filename = "./NEWS.md"
start_string = "<!-- towncrier release notes start -->\n"
title_format = "{name} {version} ({project_date})"

[[tool.towncrier.type]]
directory = "added"
name = "â• Added"
showcontent = true

[[tool.towncrier.type]]
directory = "fixed"
name = "ğŸ”§ Fixed"
showcontent = true

[[tool.towncrier.type]]
directory = "changed"
name = "ğŸ”„ Changed"
showcontent = true

[[tool.towncrier.type]]
directory = "deprecation"
name = "â² Deprecated"
showcontent = true

[[tool.towncrier.type]]
directory = "removed"
name = "ğŸ—‘ Removed"
showcontent = true

[[tool.towncrier.type]]
directory = "security"
name = "ğŸ›¡ Security"
showcontent = true